{
 "title": "Cowrie",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Live", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Login Attempts",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "{job=\"cowrie\"} |= `cowrie.login.success`"
    }
   ]
  },
  {
   "title": "Commands Executed",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "{job=\"cowrie\"} |= `cowrie.command.input` | json | label_format Source=\"{{.src_ip}}\", Command=\"{{.input}}\""
    }
   ]
  },
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Top Attacking IPs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "topk(10, sum by (src_ip) (count_over_time({job=\"cowrie\"} | json | src_ip!=\"\" [$__range])))"
    }
   ]
  },
  {
   "title": "Top Commands",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "topk(10, sum by (input) (count_over_time({job=\"cowrie\"} | json | input!=\"\" [$__range])))"
    }
   ]
  },
  {
   "title": "Top Usernames",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "topk(10, sum by (username) (count_over_time({job=\"cowrie\"} | json | username!=\"\" [$__range])))"
    }
   ]
  },
  {
   "title": "Top Passwords",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "topk(10, sum by (password) (count_over_time({job=\"cowrie\"} | json | password!=\"\" [$__range])))"
    }
   ]
  }
 ]
}